vich_uploader:
    db_driver: orm

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
    mappings:
        scientistsStudies:
            uri_prefix: /uploads/scientistsstudies
            upload_destination: '%kernel.project_dir%/public/uploads/scientistsstudies'
            namer: vich_uploader.namer_origname
        report:
            uri_prefix: /uploads/reports
            upload_destination: '%kernel.project_dir%/public/uploads/reports'
            namer: vich_uploader.namer_origname
